### PR TITLE
fix: correct audio frequency decoding script. fixes #11

### LINKED ISSUE #11: Audio frequency issues
Two types of issues have been discussed related to audio frequency:
 
(checked when fixed)

- [ ] On recordings done on "LOW", decoding has not been possible
- [ ] There's a sample frequency difference in the audios recorded with the firmware after the 2024 FW updates
- [ ] We don't clearly document the process of decoding the audio or how the frequency is obtained

### PR DESCRIPTION
**Pull request by Josfemova**
Fixes the audio parser script and adds documentation that explains how the frequency for decoding is obtained. Solves #11

### CODE REVIEW

**Comment by Josfemova** [comment]
@Era-Dorta  let me know what an useful frequency would be for low frequency audio, I thought that perhaps the decimation factor of 8 was too high but it was the last at which I could sort of understand human speech.

File: microphone/drv_audio_pdm.h [hunk 1]
```diff
@@ -8,7 +8,7 @@
 
 #define PDM_BUF_NUM 	2
 #define PDM_BUF_SIZE 	2048
-#define DECIMATION		32
+#define DECIMATION		8
```
Comment (Era-Dorta) [inline microphone/drv_audio_pdm.h:11]: See main comment, about how high the decimation should be

File: BadgeFramework/audio_parser_V0.py [hunk 2]
```diff
@@ -15,12 +26,11 @@ def main(fn):
 
             path_wav_output = path_raw_input.parent / (path_raw_input.stem + ".wav")
 
+            buffer_dtype = np.int16 # 16-bit PCM
             if path_raw_input.stem[4:6] == "LO":
                 sample_rate = LOW_SAMPLE_RATE  # Low frequency sampling
-                buffer_dtype = np.int16 # 16-bit PCM
             elif path_raw_input.stem[4:6] == "HI":
                 sample_rate = HIGH_SAMPLE_RATE  # High frequency sampling
-                buffer_dtype = np.int32 # 32-bit PCM
```
Comment (Era-Dorta) [inline BadgeFramework/audio_parser_V0.py:23]: Do you have an idea why in the old samples where at 32 bit? As I understand it's just about quality of the audio, isn't it?

**Review by Era-Dorta — COMMENTED** [review]
I'm still a bit confused by all of this. I think the main point here is that low frequency should be 1250Hz. For the high frequency, I'd prefer as high as it gets but still within the predefined values of audacity:  8000, 11025, 16000, 22050, 32000, 44100 or 48000 Hz

File: microphone/drv_audio_pdm.h (hunk 1 above)
Comment (Josfemova) [reply microphone/drv_audio_pdm.h:11]: `LOW` targeted 625 Hz before, why is the requirement changing to target  ~1250 Hz? Where does 1250 Hz come from?

File: BadgeFramework/audio_parser_V0.py (hunk 2 above)
Comment (Josfemova) [reply BadgeFramework/audio_parser_V0.py:23]: to note: the decoding script might have worked because it assumed 32 bit PCM but assumed sample rate was half the actual sample rate (8K instead of 16K)

Comment (Era-Dorta) [reply BadgeFramework/audio_parser_V0.py:23]: OMG, this explains a lot actually. Then I'm happy with this change.

File: microphone/drv_audio_pdm.h (hunk 1 above)
Comment (Josfemova) [reply microphone/drv_audio_pdm.h:11]: to be clear, only frequencies allowed would be the result of dividing the PDM clock by and integer, a nice split of 2048 being better,  doing some more precise calculations, with our config:

x = PDM_CLOCK = (32.768/ 30)/64 = 17.066 KHz

Some possible decimation factors
x/16 ~ 1.066 KHz 
x/14 ~ 1.219 KHz
x/13 ~ 1.312 KHz
...
x/8 ~ 2.133 KHz

Comment (Era-Dorta) [reply microphone/drv_audio_pdm.h:11]: I'm still unsure on what do here, the 1250Hz with 16 bit sample depth decoding script worked fine with some the raw conflab audio files. That means the midge was flashed to do that. I guess with the undocumented clock frequency flag. Is that something that we can replicate or as you say it needs a modified SDK?

Comment (Josfemova) [reply microphone/drv_audio_pdm.h:11]: I can try replicating, but do we actually want to complicate the SDK setup process just to keep a sampling frequency for which we have no other justification than "that's what it was". If 1KHz could work fine, why complicate the setup process just to keep 1.250KHz?

Comment (Josfemova) [reply microphone/drv_audio_pdm.h:11]: Perhaps this is a topic to discuss in the biweekly (? What are the requirements for the LOW frequency and such

Comment (Era-Dorta) [reply microphone/drv_audio_pdm.h:11]: Fair point about complicating the SDK setup. In this case, I think we should go for:
low frequency: 1000 Hz and high frequency 16000 Hz, which is `PDM_CLK_DIV = 32` and `DECIMATION = 16`. As this gives us nice rounded numbers. I'll check in with Hayley to make sure she's happy with this change.

I also realised that Audacity supports inputting any value for the sample rate, if you just edit the text field.

File: BadgeFramework/audio_parser_V0.py [hunk 3]
```diff
@@ -2,8 +2,19 @@
 from scipy.io.wavfile import write
 from pathlib import Path
 
-HIGH_SAMPLE_RATE = 8000
-LOW_SAMPLE_RATE = 1250
+PDM_CRYSTAL_CLK = 32.768e6 # Frequency that feeds the PDM clock generator
```
Comment (Era-Dorta) [inline BadgeFramework/audio_parser_V0.py:5]: To leave things documented here too. Where is this one coming from?

I still don't understand why the values that you have here do not match the ones in this thread https://discord.com/channels/1342526858750722108/1342526858750722111/1353803614644076555

There we have DIV25: 0x0A000000 -> CLK: 1.280 MHz -> SR: 20000 Hz but here the same factor `((32.768e6 / 25) / 64) = 20480`. Do they have a `PDM_CRYSTAL_CLK` at a different frequency?

Comment (Josfemova) [reply BadgeFramework/audio_parser_V0.py:5]: digging further: this is a good catch, I confused the two clk source crystals. There is a 32MHz high freq clock, but I confused it with the lower 32.768 KHz crystal used for bl radio. the data is extracted from the BMD-300 datasheet although it's also documented in the datasheet for the nrf52832

File: microphone/drv_audio_pdm.h (hunk 1 above)
Comment (Josfemova) [reply microphone/drv_audio_pdm.h:11]: Need to dig a little bit more as it seems some of the stuff I remember from the SDK could be wrong? 
Digging the current repo I can see the config function directly writing the value for 20KHz in the register, but I remember there being a function that did a precheck in the middle (? Also I remember that bosco saw the register falling back to a default value when using the code from Ioannis? Anyways, will dig some more to get a better understanding

File: BadgeFramework/audio_parser_V0.py (hunk 3 above)
Comment (Josfemova) [reply BadgeFramework/audio_parser_V0.py:5]: Also was mislead by the common practice in the HW design industry of applying the floor function to any frequency value in documentation, my bad

File: microphone/drv_audio_pdm.h (hunk 1 above)
Comment (Era-Dorta) [reply microphone/drv_audio_pdm.h]: Amazing, thanks a lot for getting to the bottom on this.

File: microphone/drv_audio_pdm.c [hunk 4]
```diff
@@ -161,8 +161,11 @@ ret_code_t drv_audio_init(nrf_pdm_mode_t mode)
 
 	pdm_cfg.mode        = local_mode;
 
-	// 20kHz
-	pdm_cfg.clock_freq	= 0x08800000;
+	//! Not officially supported value corresponding to PDM_CLK of 
+	//! NRF_PDM_FREQ_1280K, which will result in a 20KHz sample rate for HI
+	//! position. The HW in the uC is designed for this frequency but Nordic 
+	//! does not support it oficially as it's not considered tested enough
```
Comment (Era-Dorta) [inline microphone/drv_audio_pdm.c:167]: Should we add a link here also to the thread? So that we can find it easily again?

File: BadgeFramework/audio_parser_V0.py (hunk 3 above)
Comment (Era-Dorta) [reply BadgeFramework/audio_parser_V0.py]: Nice, how about the the `int` flooring also for the floating point values when you do the calculation?

```python
HIGH_SAMPLE_RATE = int((PDM_CRYSTAL_CLK / PDM_CLK_DIV) / PDM_TO_PCM_DIV)

# In LOW mode the midge will store one sample per DECIMATION samples
DECIMATION = 8
LOW_SAMPLE_RATE = int(HIGH_SAMPLE_RATE/DECIMATION)
```

I don't understand the details of how the audio data is stored. So I don't know how that should be handled. I'm also fine having an `assert` or an `raise NotImplementedError` or similar for different values. To indicate that they should never be changed.

File: microphone/drv_audio_pdm.h [hunk 5]
```diff
@@ -8,7 +8,7 @@
 
 #define PDM_BUF_NUM 	2
 #define PDM_BUF_SIZE 	2048
-#define DECIMATION		32
+#define DECIMATION		16 // 20KHz/16 = 1.250 KHz sample rate for LO position
```
Comment (Era-Dorta) [inline microphone/drv_audio_pdm.h:11]: Add assert that buffer needs to be a size that is divisible by the low sample rate

File: microphone/drv_audio_pdm.h (hunk 1 above)
Comment (Era-Dorta) [reply microphone/drv_audio_pdm.h]: We talked about this in the meeting. For the current version of the SDK, we do not need to edit it. Jose already checked that the register is not set back to the default value and the audio files can be decoded with the frequencies that we are setting. Please mark as resolved after you read this.

File: BadgeFramework/audio_parser_V0.py (hunk 3 above)
Comment (Era-Dorta) [reply BadgeFramework/audio_parser_V0.py]: As discussed in the meeting, the `write` function requires the `rate` to be an integer.  So that is why the `int` is there. The buffer gets filled at the floating point frequency but there is no point if we cannot convert it to `wav` due to this limitation. Also, please close once you read this.

File: microphone/drv_audio_pdm.h (hunk 5 above)
Comment (Era-Dorta) [reply microphone/drv_audio_pdm.h:11]: I think, we also need to change the `test.py`. The `PDM_CLK_DIV` frequency is changed https://github.com/TUDelft-SPC-Lab/midge-code/blob/master/BadgeFramework/test.py#L22 and https://github.com/TUDelft-SPC-Lab/midge-code/blob/master/BadgeFramework/test.py#L62 . That means the `assert` would fail for them, wouldn't it?

Comment (Josfemova) [reply microphone/drv_audio_pdm.h:12]: added both the static assert and fixed the code that was decoding the frequency value. Also updated the `test.py` file to make sure we check for the "overclocked" PDM freq

File: Makefile [hunk 6]
```diff
@@ -232,6 +232,7 @@ CFLAGS += -ffunction-sections -fdata-sections -fno-strict-aliasing
 CFLAGS += -fno-builtin -fshort-enums
 CFLAGS += -D__HEAP_SIZE=1024
 CFLAGS += -D__STACK_SIZE=4096
+CFLAGS += -std=gnu23
```
Comment (Era-Dorta) [inline Makefile:235]: Why was this change needed?

**Review by Era-Dorta — APPROVED** [review]
This looks really good. Very happy with it now, thanks :)

File: Makefile (hunk 6 above)
Comment (Josfemova) [reply Makefile:235]: Default standard setup in the compiler did not have `static_assert` defined, probably was selecting a std before C11. Explicitly selected C23 as it's the latest supported std

Comment (Era-Dorta) [reply Makefile:235]: Thanks for the clarification, do you think using the new standard might cause any bugs? I have no idea on forwards compatibly between C++ standards.

Comment (Josfemova) [reply Makefile:235]: In general the C standard is very conservative. Forward compatibility is essentially a certainty unless one uses "reserved" identifiers or "exquisite" voodoo which is replaced by functionality in newer standards. 

No C23 (nor C17) features are being used in the code as of now, technically C11 would be enough.

No reserved identifiers that collide with functionality included up to C23 are in use either,  and no vodoo that is exposed to C standard updates is being used.

In summary, updating the standard used to compile should not affect the functionality of the firmware apart from providing the "new" functionality

Comment (Era-Dorta) [reply Makefile:235]: Great, thanks for explaining. Please, go ahead, mark this as resolved and merge the PR.
